# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SJBR\StaticInfoTables\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  SJBR\StaticInfoTables\EventListener\AfterPackageActivationEventListener:
    tags:
      - name: event.listener
        identifier: 'staticInfoTablesListener'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent